insertion-sort: insertion-sort.cpp
	g++ -std=c++20 -g insertion-sort.cpp -o insertion-sort

merge-sort: merge-sort.cpp
	g++ -std=c++20 -g merge-sort.cpp -o merge-sort

bubble_sort: bubble_sort.cpp
	g++ -std=c++20 -g bubble-sort.cpp -o bubble-sort

.PHONEY: clean

clean:
	rm -f insertion-sort merge-sort bubble-sort
