insertion-sort: insertion-sort.cpp
	g++ -std=c++20 -g insertion-sort.cpp -o insertion-sort

merge-sort: merge-sort.cpp
	g++ -std=c++20 -g merge-sort.cpp -o merge-sort

.PHONEY: clean

clean:
	rm -f insertion-sort merge-sort
